// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUZTbmoxThGggqyGhjp81NoCz1Ch1mhrM',
    appId: '1:211527808213:web:4a82b8e25c2d137bb9de5c',
    messagingSenderId: '211527808213',
    projectId: 'travel-45dae',
    authDomain: 'travel-45dae.firebaseapp.com',
    storageBucket: 'travel-45dae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKLdhS3gpC-v0P7AYKnrzuSL0Fr2nhRLw',
    appId: '1:211527808213:android:262bc30072c86350b9de5c',
    messagingSenderId: '211527808213',
    projectId: 'travel-45dae',
    storageBucket: 'travel-45dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ZNJKnbnqn5SUPF82vP8C_iWaQbhS_sY',
    appId: '1:211527808213:ios:6c8448e1dfdc006db9de5c',
    messagingSenderId: '211527808213',
    projectId: 'travel-45dae',
    storageBucket: 'travel-45dae.appspot.com',
    iosBundleId: 'com.example.exploreandtrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ZNJKnbnqn5SUPF82vP8C_iWaQbhS_sY',
    appId: '1:211527808213:ios:6c8448e1dfdc006db9de5c',
    messagingSenderId: '211527808213',
    projectId: 'travel-45dae',
    storageBucket: 'travel-45dae.appspot.com',
    iosBundleId: 'com.example.exploreandtrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUZTbmoxThGggqyGhjp81NoCz1Ch1mhrM',
    appId: '1:211527808213:web:aafd9c989ac85d88b9de5c',
    messagingSenderId: '211527808213',
    projectId: 'travel-45dae',
    authDomain: 'travel-45dae.firebaseapp.com',
    storageBucket: 'travel-45dae.appspot.com',
  );
}
